config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'pins#index'
  get 'home/about'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
    belongs_to :user
    has_attached_file :image, styles: { :medium => "300x300>", :thumb => "100x100>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy
  ]

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  end

  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin został stworzony!' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin został pomyślnie zmieniony.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin został pomyślnie usunięty.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :name)
    end
    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Nie możesz edytować tego pinu!" if @pin.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data- 6 toggle data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'obrazkowo', root_path, class: 'navbar-brand' %>
    </div>
<!-- Collect the nv links, forms, and other content for logging -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Strona główna', root_path %></li>
        <li><%= link_to 'Lista pinów', pins_path %></li>
        <li><%= link_to 'O mnie', home_about_path %></li>
        <% if user_signed_in? %>   
          <li><%= link_to 'Nowy pin', new_pin_path %></li>
          <li><%= link_to 'Edycja profilu', edit_user_registration_path %></li>
          <li><%= link_to 'Wyloguj', destroy_user_session_path, method: :delete %></li>
        
        <% else %>
          <li><%= link_to 'Zaloguj', new_user_session_path %></li>
          <li><%= link_to 'Zarejestruj', new_user_registration_path %></li>
        <% end %>
    </ul>    
  </div><!-- /.navbar-collapse -->
 </div><!-- /.container-fluid -->
</div>

app/views/home/about.html.erb
<h1> O MNIE </h1>
<p> Jestem Roxa</p>

app/views/home/index.html.erb
<div class="jumbotron">
<h1>Siema, to moja aplikacja!</h1>
<p>W końcu się nauczę!</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>obrazkowo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
<%= render 'home/header' %>

<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>
<%= yield %>
</div>

</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f|%>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :image, "OBRAZ:" %>
    <%= f.file_field :image, class: "form-control" %><br>
  </div>

  <div class="form-group">
    <%= f.label :OPIS %><br>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit "Utwórz!", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>EDYTUJ</h1>

<%= render 'form' %>

<%= link_to 'POKAŻ', @pin %> |
<%= link_to 'COFNIJ', pins_path %>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
    <% @pins.each do |pin| %>
      <div class="box">
          <div class="panel panel-default">
            <%= link_to image_tag(pin.image.url(:medium)), pin %><br/>
            <div class="panel-body">
                <%= pin.description %><br/>
                <br/><strong><%= pin.user.name if pin.user %></strong><br/>
            </div>
         <% if pin.user == current_user %>
             <div class="panel-footer">
              <%= link_to 'EDYTUJ', edit_pin_path(pin) %><br/>
              <%= link_to 'USUŃ', pin, method: :delete, data: { confirm: 'Czy jesteś pewny?' } %><br/>
             </div>
        <% end %>
        </div>
      </div>
    <% end %>

</div>
<div class="center">
<%= will_paginate @posts, renderer: BootstrapPagination::Rails%>
</div>

app/views/pins/new.html.erb
<h1>NOWY</h1>

<%= render 'form' %>

<%= link_to 'WRÓĆ', pins_path %>

app/views/pins/show.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
      <div class="panel panel default">
        <div class="panel-heading center"><%= image_tag @pin.image.url(:medium) %></div>
        <div class="panel-body">
          <%= @pin.description %><br/>
          <br/><%= @pin.user.name %><br/>  
          <% if @pin.user == current_user %>
              <%= link_to 'EDYTUJ', edit_pin_path(@pin) %> |
          <% end %>
          <%= link_to 'WRÓĆ', pins_path %>
      </div>
    </div>
  </div>
</div>